/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * IacApiErrorResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class IacApiErrorResponse {

  @JsonProperty("errors")

  private List<IacApiError> errors = new ArrayList<>();
  public IacApiErrorResponse errors(List<IacApiError> errors) {
    this.errors = errors;
    return this;
  }

  public IacApiErrorResponse addErrorsItem(IacApiError errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

  /**
  * Get errors
  * @return errors
  **/
  @Schema(required = true, description = "")
  public List<IacApiError> getErrors() {
    return errors;
  }
  public void setErrors(List<IacApiError> errors) {
    this.errors = errors;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IacApiErrorResponse iacApiErrorResponse = (IacApiErrorResponse) o;
    return Objects.equals(this.errors, iacApiErrorResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IacApiErrorResponse {\n");
    
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
