/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * IacMatchedPoliciesSummary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class IacMatchedPoliciesSummary {

  @JsonProperty("high")

  private Long high = null;

  @JsonProperty("medium")

  private Long medium = null;

  @JsonProperty("low")

  private Long low = null;
  public IacMatchedPoliciesSummary high(Long high) {
    this.high = high;
    return this;
  }

  

  /**
  * Number of high severity policies matched
  * @return high
  **/
  @Schema(example = "6", description = "Number of high severity policies matched")
  public Long getHigh() {
    return high;
  }
  public void setHigh(Long high) {
    this.high = high;
  }
  public IacMatchedPoliciesSummary medium(Long medium) {
    this.medium = medium;
    return this;
  }

  

  /**
  * Number of medium severity policies matched
  * @return medium
  **/
  @Schema(example = "15", description = "Number of medium severity policies matched")
  public Long getMedium() {
    return medium;
  }
  public void setMedium(Long medium) {
    this.medium = medium;
  }
  public IacMatchedPoliciesSummary low(Long low) {
    this.low = low;
    return this;
  }

  

  /**
  * Number of low severity policies matched
  * @return low
  **/
  @Schema(example = "20", description = "Number of low severity policies matched")
  public Long getLow() {
    return low;
  }
  public void setLow(Long low) {
    this.low = low;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IacMatchedPoliciesSummary iacMatchedPoliciesSummary = (IacMatchedPoliciesSummary) o;
    return Objects.equals(this.high, iacMatchedPoliciesSummary.high) &&
        Objects.equals(this.medium, iacMatchedPoliciesSummary.medium) &&
        Objects.equals(this.low, iacMatchedPoliciesSummary.low);
  }

  @Override
  public int hashCode() {
    return Objects.hash(high, medium, low);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IacMatchedPoliciesSummary {\n");
    
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
