/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * IacPolicyViolationAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class IacPolicyViolationAttributes {

  @JsonProperty("severity")

  private IacPolicySeverity severity = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("rule")

  private String rule = null;

  @JsonProperty("desc")

  private String desc = null;

  @JsonProperty("systemDefault")

  private Boolean systemDefault = null;

  @JsonProperty("files")

  private List<String> files = null;

  @JsonProperty("policyId")

  private UUID policyId = null;

  @JsonProperty("docUrl")

  private String docUrl = null;
  public IacPolicyViolationAttributes severity(IacPolicySeverity severity) {
    this.severity = severity;
    return this;
  }

  

  /**
  * Get severity
  * @return severity
  **/
  @Schema(description = "")
  public IacPolicySeverity getSeverity() {
    return severity;
  }
  public void setSeverity(IacPolicySeverity severity) {
    this.severity = severity;
  }
  public IacPolicyViolationAttributes name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Policy name
  * @return name
  **/
  @Schema(example = "AWS Security Groups allow internet traffic to SSH port (22)", description = "Policy name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public IacPolicyViolationAttributes rule(String rule) {
    this.rule = rule;
    return this;
  }

  

  /**
  * Violated rule
  * @return rule
  **/
  @Schema(example = "$.resource[*].aws_security_group exists and ($.resource.aws_security_group[*].ingress.cidr_blocks contains 0.0.0.0/0", description = "Violated rule")
  public String getRule() {
    return rule;
  }
  public void setRule(String rule) {
    this.rule = rule;
  }
  public IacPolicyViolationAttributes desc(String desc) {
    this.desc = desc;
    return this;
  }

  

  /**
  * Policy description
  * @return desc
  **/
  @Schema(example = "This policy identifies AWS Security Groups which do allow inbound traffic on SSH port (22) from public internet", description = "Policy description")
  public String getDesc() {
    return desc;
  }
  public void setDesc(String desc) {
    this.desc = desc;
  }
  public IacPolicyViolationAttributes systemDefault(Boolean systemDefault) {
    this.systemDefault = systemDefault;
    return this;
  }

  

  /**
  * Get systemDefault
  * @return systemDefault
  **/
  @Schema(description = "")
  public Boolean isSystemDefault() {
    return systemDefault;
  }
  public void setSystemDefault(Boolean systemDefault) {
    this.systemDefault = systemDefault;
  }
  public IacPolicyViolationAttributes files(List<String> files) {
    this.files = files;
    return this;
  }

  public IacPolicyViolationAttributes addFilesItem(String filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

  /**
  * Files
  * @return files
  **/
  @Schema(example = "[\"./main.tf\"]", description = "Files")
  public List<String> getFiles() {
    return files;
  }
  public void setFiles(List<String> files) {
    this.files = files;
  }
  public IacPolicyViolationAttributes policyId(UUID policyId) {
    this.policyId = policyId;
    return this;
  }

  

  /**
  * Policy ID
  * @return policyId
  **/
  @Schema(description = "Policy ID")
  public UUID getPolicyId() {
    return policyId;
  }
  public void setPolicyId(UUID policyId) {
    this.policyId = policyId;
  }
  public IacPolicyViolationAttributes docUrl(String docUrl) {
    this.docUrl = docUrl;
    return this;
  }

  

  /**
  * Get docUrl
  * @return docUrl
  **/
  @Schema(example = "https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-policy-reference/configuration-policies/configuration-policies-build-phase/amazon-web-services-configuration-policies/policy_617b9138-584b-4e8e-ad15-7fbabafbed1a.html", description = "")
  public String getDocUrl() {
    return docUrl;
  }
  public void setDocUrl(String docUrl) {
    this.docUrl = docUrl;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IacPolicyViolationAttributes iacPolicyViolationAttributes = (IacPolicyViolationAttributes) o;
    return Objects.equals(this.severity, iacPolicyViolationAttributes.severity) &&
        Objects.equals(this.name, iacPolicyViolationAttributes.name) &&
        Objects.equals(this.rule, iacPolicyViolationAttributes.rule) &&
        Objects.equals(this.desc, iacPolicyViolationAttributes.desc) &&
        Objects.equals(this.systemDefault, iacPolicyViolationAttributes.systemDefault) &&
        Objects.equals(this.files, iacPolicyViolationAttributes.files) &&
        Objects.equals(this.policyId, iacPolicyViolationAttributes.policyId) &&
        Objects.equals(this.docUrl, iacPolicyViolationAttributes.docUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(severity, name, rule, desc, systemDefault, files, policyId, docUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IacPolicyViolationAttributes {\n");
    
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rule: ").append(toIndentedString(rule)).append("\n");
    sb.append("    desc: ").append(toIndentedString(desc)).append("\n");
    sb.append("    systemDefault: ").append(toIndentedString(systemDefault)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    policyId: ").append(toIndentedString(policyId)).append("\n");
    sb.append("    docUrl: ").append(toIndentedString(docUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
