/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.*;

/**
 * IacTemplateParameters
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class IacTemplateParameters {

  @JsonProperty("variables")

  private Map<String, String> variables = null;

  @JsonProperty("variableFiles")

  private List<String> variableFiles = null;

  @JsonProperty("policyIdFilters")

  private List<String> policyIdFilters = null;

  @JsonProperty("files")

  private List<String> files = null;

  @JsonProperty("folders")

  private List<String> folders = null;

  @JsonProperty("scanPlanFilesOnly")

  private Boolean scanPlanFilesOnly = false;
  public IacTemplateParameters variables(Map<String, String> variables) {
    this.variables = variables;
    return this;
  }

  
  public IacTemplateParameters putVariablesItem(String key, String variablesItem) {
    if (this.variables == null) {
      this.variables = new HashMap<>();
    }
    this.variables.put(key, variablesItem);
    return this;
  }
  /**
  * Template variables and values list to be used for evaluation
  * @return variables
  **/
  @Schema(example = "{\"region\":\"us-east-1\",\"image_id\":\"amzn2-ami-hvm-2.0\"}", description = "Template variables and values list to be used for evaluation")
  public Map<String, String> getVariables() {
    return variables;
  }
  public void setVariables(Map<String, String> variables) {
    this.variables = variables;
  }
  public IacTemplateParameters variableFiles(List<String> variableFiles) {
    this.variableFiles = variableFiles;
    return this;
  }

  public IacTemplateParameters addVariableFilesItem(String variableFilesItem) {
    if (this.variableFiles == null) {
      this.variableFiles = new ArrayList<>();
    }
    this.variableFiles.add(variableFilesItem);
    return this;
  }

  /**
  * Names of template variable files inside the template package to be used. Specify file path relative to the root of the zip file you uploaded
  * @return variableFiles
  **/
  @Schema(example = "[\"./dev.tfvars\",\"./us/qa.tfvars\"]", description = "Names of template variable files inside the template package to be used. Specify file path relative to the root of the zip file you uploaded")
  public List<String> getVariableFiles() {
    return variableFiles;
  }
  public void setVariableFiles(List<String> variableFiles) {
    this.variableFiles = variableFiles;
  }
  public IacTemplateParameters policyIdFilters(List<String> policyIdFilters) {
    this.policyIdFilters = policyIdFilters;
    return this;
  }

  public IacTemplateParameters addPolicyIdFiltersItem(String policyIdFiltersItem) {
    if (this.policyIdFilters == null) {
      this.policyIdFilters = new ArrayList<>();
    }
    this.policyIdFilters.add(policyIdFiltersItem);
    return this;
  }

  /**
  * If list is populated, IaC scan service will evaluate with only policies that have IDs in this list
  * @return policyIdFilters
  **/
  @Schema(description = "If list is populated, IaC scan service will evaluate with only policies that have IDs in this list")
  public List<String> getPolicyIdFilters() {
    return policyIdFilters;
  }
  public void setPolicyIdFilters(List<String> policyIdFilters) {
    this.policyIdFilters = policyIdFilters;
  }
  public IacTemplateParameters files(List<String> files) {
    this.files = files;
    return this;
  }

  public IacTemplateParameters addFilesItem(String filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

  /**
  * If you specify file paths, the IaC scan service will evaluate only files in this list. Specify file paths relative to the root of the zip file you uploaded
  * @return files
  **/
  @Schema(example = "[\"./dev/auto_scale.tf\",\"./dev/app.tf\"]", description = "If you specify file paths, the IaC scan service will evaluate only files in this list. Specify file paths relative to the root of the zip file you uploaded")
  public List<String> getFiles() {
    return files;
  }
  public void setFiles(List<String> files) {
    this.files = files;
  }
  public IacTemplateParameters folders(List<String> folders) {
    this.folders = folders;
    return this;
  }

  public IacTemplateParameters addFoldersItem(String foldersItem) {
    if (this.folders == null) {
      this.folders = new ArrayList<>();
    }
    this.folders.add(foldersItem);
    return this;
  }

  /**
  * If you specify folder paths, the IaC scan service will evaluate only folders in the list. Specify folder paths relative to the root of the zip file you uploaded
  * @return folders
  **/
  @Schema(example = "[\"./dev\",\"./under_develop\",\"./modules/dev\"]", description = "If you specify folder paths, the IaC scan service will evaluate only folders in the list. Specify folder paths relative to the root of the zip file you uploaded")
  public List<String> getFolders() {
    return folders;
  }
  public void setFolders(List<String> folders) {
    this.folders = folders;
  }
  public IacTemplateParameters scanPlanFilesOnly(Boolean scanPlanFilesOnly) {
    this.scanPlanFilesOnly = scanPlanFilesOnly;
    return this;
  }

  

  /**
  * If you specify this option, the IaC scan service will evaluate only the plan files and ignore the rest
  * @return scanPlanFilesOnly
  **/
  @Schema(description = "If you specify this option, the IaC scan service will evaluate only the plan files and ignore the rest")
  public Boolean isScanPlanFilesOnly() {
    return scanPlanFilesOnly;
  }
  public void setScanPlanFilesOnly(Boolean scanPlanFilesOnly) {
    this.scanPlanFilesOnly = scanPlanFilesOnly;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IacTemplateParameters iacTemplateParameters = (IacTemplateParameters) o;
    return Objects.equals(this.variables, iacTemplateParameters.variables) &&
        Objects.equals(this.variableFiles, iacTemplateParameters.variableFiles) &&
        Objects.equals(this.policyIdFilters, iacTemplateParameters.policyIdFilters) &&
        Objects.equals(this.files, iacTemplateParameters.files) &&
        Objects.equals(this.folders, iacTemplateParameters.folders) &&
        Objects.equals(this.scanPlanFilesOnly, iacTemplateParameters.scanPlanFilesOnly);
  }

  @Override
  public int hashCode() {
    return Objects.hash(variables, variableFiles, policyIdFilters, files, folders, scanPlanFilesOnly);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IacTemplateParameters {\n");
    
    sb.append("    variables: ").append(toIndentedString(variables)).append("\n");
    sb.append("    variableFiles: ").append(toIndentedString(variableFiles)).append("\n");
    sb.append("    policyIdFilters: ").append(toIndentedString(policyIdFilters)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    folders: ").append(toIndentedString(folders)).append("\n");
    sb.append("    scanPlanFilesOnly: ").append(toIndentedString(scanPlanFilesOnly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
