/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Links related to the scan
 */
@Schema(description = "Links related to the scan")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScansResponseLinks {

  @JsonProperty("self")

  private String self = null;

  @JsonProperty("first")

  private String first = null;

  @JsonProperty("prev")

  private String prev = null;

  @JsonProperty("next")

  private String next = null;

  @JsonProperty("last")

  private String last = null;
  public JsonApiModelScansResponseLinks self(String self) {
    this.self = self;
    return this;
  }

  

  /**
  * Get self
  * @return self
  **/
  @Schema(example = "/scans?timeType=to_now&filter[resourceList]=prisma-devops&page[size]=10&page[number]=3", description = "")
  public String getSelf() {
    return self;
  }
  public void setSelf(String self) {
    this.self = self;
  }
  public JsonApiModelScansResponseLinks first(String first) {
    this.first = first;
    return this;
  }

  

  /**
  * Get first
  * @return first
  **/
  @Schema(example = "/scans?timeType=to_now&filter[resourceList]=prisma-devops&page[size]=10&page[number]=1", description = "")
  public String getFirst() {
    return first;
  }
  public void setFirst(String first) {
    this.first = first;
  }
  public JsonApiModelScansResponseLinks prev(String prev) {
    this.prev = prev;
    return this;
  }

  

  /**
  * Get prev
  * @return prev
  **/
  @Schema(example = "/scans?timeType=to_now&filter[resourceList]=prisma-devops&page[size]=10&page[number]=2", description = "")
  public String getPrev() {
    return prev;
  }
  public void setPrev(String prev) {
    this.prev = prev;
  }
  public JsonApiModelScansResponseLinks next(String next) {
    this.next = next;
    return this;
  }

  

  /**
  * Get next
  * @return next
  **/
  @Schema(example = "/scans?timeType=to_now&filter[resourceList]=prisma-devops&page[size]=10&page[number]=4", description = "")
  public String getNext() {
    return next;
  }
  public void setNext(String next) {
    this.next = next;
  }
  public JsonApiModelScansResponseLinks last(String last) {
    this.last = last;
    return this;
  }

  

  /**
  * Get last
  * @return last
  **/
  @Schema(example = "/scans?timeType=to_now&filter[resourceList]=prisma-devops&page[size]=10&page[number]=256", description = "")
  public String getLast() {
    return last;
  }
  public void setLast(String last) {
    this.last = last;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelScansResponseLinks jsonApiModelScansResponseLinks = (JsonApiModelScansResponseLinks) o;
    return Objects.equals(this.self, jsonApiModelScansResponseLinks.self) &&
        Objects.equals(this.first, jsonApiModelScansResponseLinks.first) &&
        Objects.equals(this.prev, jsonApiModelScansResponseLinks.prev) &&
        Objects.equals(this.next, jsonApiModelScansResponseLinks.next) &&
        Objects.equals(this.last, jsonApiModelScansResponseLinks.last);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, first, prev, next, last);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScansResponseLinks {\n");
    
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    first: ").append(toIndentedString(first)).append("\n");
    sb.append("    prev: ").append(toIndentedString(prev)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
