/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * JsonApiModelAsyncScanRequestData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelAsyncScanRequestData {

  @JsonProperty("type")

  private String type = null;

  @JsonProperty("attributes")

  private JsonApiModelAsyncScanRequestDataAttributes attributes = null;
  public JsonApiModelAsyncScanRequestData type(String type) {
    this.type = type;
    return this;
  }

  

  /**
  * The required value must currently be async-scan
  * @return type
  **/
  @Schema(example = "async-scan", description = "The required value must currently be async-scan")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public JsonApiModelAsyncScanRequestData attributes(JsonApiModelAsyncScanRequestDataAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

  

  /**
  * Get attributes
  * @return attributes
  **/
  @Schema(required = true, description = "")
  public JsonApiModelAsyncScanRequestDataAttributes getAttributes() {
    return attributes;
  }
  public void setAttributes(JsonApiModelAsyncScanRequestDataAttributes attributes) {
    this.attributes = attributes;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelAsyncScanRequestData jsonApiModelAsyncScanRequestData = (JsonApiModelAsyncScanRequestData) o;
    return Objects.equals(this.type, jsonApiModelAsyncScanRequestData.type) &&
        Objects.equals(this.attributes, jsonApiModelAsyncScanRequestData.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, attributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelAsyncScanRequestData {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
