/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * JsonApiModelScansResponseMeta
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScansResponseMeta {

  @JsonProperty("pass")

  private Long pass = null;

  @JsonProperty("fail")

  private Long fail = null;

  @JsonProperty("all")

  private Long all = null;

  @JsonProperty("matchedPoliciesSummary")

  private IacMatchedPoliciesSummary matchedPoliciesSummary = null;
  public JsonApiModelScansResponseMeta pass(Long pass) {
    this.pass = pass;
    return this;
  }

  

  /**
  * Total number of passed scans
  * @return pass
  **/
  @Schema(example = "100", description = "Total number of passed scans")
  public Long getPass() {
    return pass;
  }
  public void setPass(Long pass) {
    this.pass = pass;
  }
  public JsonApiModelScansResponseMeta fail(Long fail) {
    this.fail = fail;
    return this;
  }

  

  /**
  * Total number of failed scans
  * @return fail
  **/
  @Schema(example = "10", description = "Total number of failed scans")
  public Long getFail() {
    return fail;
  }
  public void setFail(Long fail) {
    this.fail = fail;
  }
  public JsonApiModelScansResponseMeta all(Long all) {
    this.all = all;
    return this;
  }

  

  /**
  * Total number of scans in the table view
  * @return all
  **/
  @Schema(example = "100", description = "Total number of scans in the table view")
  public Long getAll() {
    return all;
  }
  public void setAll(Long all) {
    this.all = all;
  }
  public JsonApiModelScansResponseMeta matchedPoliciesSummary(IacMatchedPoliciesSummary matchedPoliciesSummary) {
    this.matchedPoliciesSummary = matchedPoliciesSummary;
    return this;
  }

  

  /**
  * Get matchedPoliciesSummary
  * @return matchedPoliciesSummary
  **/
  @Schema(description = "")
  public IacMatchedPoliciesSummary getMatchedPoliciesSummary() {
    return matchedPoliciesSummary;
  }
  public void setMatchedPoliciesSummary(IacMatchedPoliciesSummary matchedPoliciesSummary) {
    this.matchedPoliciesSummary = matchedPoliciesSummary;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelScansResponseMeta jsonApiModelScansResponseMeta = (JsonApiModelScansResponseMeta) o;
    return Objects.equals(this.pass, jsonApiModelScansResponseMeta.pass) &&
        Objects.equals(this.fail, jsonApiModelScansResponseMeta.fail) &&
        Objects.equals(this.all, jsonApiModelScansResponseMeta.all) &&
        Objects.equals(this.matchedPoliciesSummary, jsonApiModelScansResponseMeta.matchedPoliciesSummary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pass, fail, all, matchedPoliciesSummary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScansResponseMeta {\n");
    
    sb.append("    pass: ").append(toIndentedString(pass)).append("\n");
    sb.append("    fail: ").append(toIndentedString(fail)).append("\n");
    sb.append("    all: ").append(toIndentedString(all)).append("\n");
    sb.append("    matchedPoliciesSummary: ").append(toIndentedString(matchedPoliciesSummary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
