/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Links related to the scan
 */
@Schema(description = "Links related to the scan")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScanTableDataRelationshipsScanResultLinks {

  @JsonProperty("related")

  private String related = null;
  public JsonApiModelScanTableDataRelationshipsScanResultLinks related(String related) {
    this.related = related;
    return this;
  }

  

  /**
  * URL to the detailed scan result object
  * @return related
  **/
  @Schema(example = "/scans/3fa85f64-5717-4562-b3fc-2c963f66afa6/results", description = "URL to the detailed scan result object")
  public String getRelated() {
    return related;
  }
  public void setRelated(String related) {
    this.related = related;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelScanTableDataRelationshipsScanResultLinks jsonApiModelScanTableDataRelationshipsScanResultLinks = (JsonApiModelScanTableDataRelationshipsScanResultLinks) o;
    return Objects.equals(this.related, jsonApiModelScanTableDataRelationshipsScanResultLinks.related);
  }

  @Override
  public int hashCode() {
    return Objects.hash(related);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScanTableDataRelationshipsScanResultLinks {\n");
    
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
