/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * JsonApiModelScanTriggerDataAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScanTriggerDataAttributes {

  @JsonProperty("templateType")

  private String templateType = null;

  @JsonProperty("templateVersion")

  private String templateVersion = null;

  @JsonProperty("templateParameters")

  private IacTemplateParameters templateParameters = null;
  public JsonApiModelScanTriggerDataAttributes templateType(String templateType) {
    this.templateType = templateType;
    return this;
  }

  

  /**
  * IaC template type. Supported types are cft, k8s, tf
  * @return templateType
  **/
  @Schema(example = "tf", required = true, description = "IaC template type. Supported types are cft, k8s, tf")
  public String getTemplateType() {
    return templateType;
  }
  public void setTemplateType(String templateType) {
    this.templateType = templateType;
  }
  public JsonApiModelScanTriggerDataAttributes templateVersion(String templateVersion) {
    this.templateVersion = templateVersion;
    return this;
  }

  

  /**
  * (optional) Template version
  * @return templateVersion
  **/
  @Schema(example = "0.13", description = "(optional) Template version")
  public String getTemplateVersion() {
    return templateVersion;
  }
  public void setTemplateVersion(String templateVersion) {
    this.templateVersion = templateVersion;
  }
  public JsonApiModelScanTriggerDataAttributes templateParameters(IacTemplateParameters templateParameters) {
    this.templateParameters = templateParameters;
    return this;
  }

  

  /**
  * Get templateParameters
  * @return templateParameters
  **/
  @Schema(description = "")
  public IacTemplateParameters getTemplateParameters() {
    return templateParameters;
  }
  public void setTemplateParameters(IacTemplateParameters templateParameters) {
    this.templateParameters = templateParameters;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelScanTriggerDataAttributes jsonApiModelScanTriggerDataAttributes = (JsonApiModelScanTriggerDataAttributes) o;
    return Objects.equals(this.templateType, jsonApiModelScanTriggerDataAttributes.templateType) &&
        Objects.equals(this.templateVersion, jsonApiModelScanTriggerDataAttributes.templateVersion) &&
        Objects.equals(this.templateParameters, jsonApiModelScanTriggerDataAttributes.templateParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateType, templateVersion, templateParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScanTriggerDataAttributes {\n");
    
    sb.append("    templateType: ").append(toIndentedString(templateType)).append("\n");
    sb.append("    templateVersion: ").append(toIndentedString(templateVersion)).append("\n");
    sb.append("    templateParameters: ").append(toIndentedString(templateParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
