/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * JsonApiModelScansResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScansResponse {

  @JsonProperty("meta")

  private JsonApiModelScansResponseMeta meta = null;

  @JsonProperty("data")

  private List<JsonApiModelScanTableData> data = new ArrayList<>();

  @JsonProperty("links")

  private JsonApiModelScansResponseLinks links = null;
  public JsonApiModelScansResponse meta(JsonApiModelScansResponseMeta meta) {
    this.meta = meta;
    return this;
  }

  

  /**
  * Get meta
  * @return meta
  **/
  @Schema(required = true, description = "")
  public JsonApiModelScansResponseMeta getMeta() {
    return meta;
  }
  public void setMeta(JsonApiModelScansResponseMeta meta) {
    this.meta = meta;
  }
  public JsonApiModelScansResponse data(List<JsonApiModelScanTableData> data) {
    this.data = data;
    return this;
  }

  public JsonApiModelScansResponse addDataItem(JsonApiModelScanTableData dataItem) {
    this.data.add(dataItem);
    return this;
  }

  /**
  * Get data
  * @return data
  **/
  @Schema(required = true, description = "")
  public List<JsonApiModelScanTableData> getData() {
    return data;
  }
  public void setData(List<JsonApiModelScanTableData> data) {
    this.data = data;
  }
  public JsonApiModelScansResponse links(JsonApiModelScansResponseLinks links) {
    this.links = links;
    return this;
  }

  

  /**
  * Get links
  * @return links
  **/
  @Schema(description = "")
  public JsonApiModelScansResponseLinks getLinks() {
    return links;
  }
  public void setLinks(JsonApiModelScansResponseLinks links) {
    this.links = links;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelScansResponse jsonApiModelScansResponse = (JsonApiModelScansResponse) o;
    return Objects.equals(this.meta, jsonApiModelScansResponse.meta) &&
        Objects.equals(this.data, jsonApiModelScansResponse.data) &&
        Objects.equals(this.links, jsonApiModelScansResponse.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, data, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScansResponse {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
