/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * JsonApiModelScanTableDataAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScanTableDataAttributes {

  @JsonProperty("name")

  private List<String> name = null;

  @JsonProperty("type")

  private List<String> type = null;

  @JsonProperty("user")

  private List<String> user = null;

  @JsonProperty("resourceList")

  private List<String> resourceList = null;

  @JsonProperty("tags")

  private List<IacScanTag> tags = null;

  @JsonProperty("failureCriteria")

  private String failureCriteria = null;

  @JsonProperty("status")

  private JsonApiModelScanStatus status = null;

  @JsonProperty("merged")

  private Boolean merged = null;

  @JsonProperty("deployed")

  private Boolean deployed = null;

  @JsonProperty("fail")

  private Long fail = null;

  @JsonProperty("pass")

  private Long pass = null;

  @JsonProperty("matchedPoliciesSummary")

  private IacMatchedPoliciesSummary matchedPoliciesSummary = null;

  @JsonProperty("scanAttributes")

  private JsonApiModelScanAttributes scanAttributes = null;

  @JsonProperty("scanTime")

  private OffsetDateTime scanTime = null;
  public JsonApiModelScanTableDataAttributes name(List<String> name) {
    this.name = name;
    return this;
  }

  public JsonApiModelScanTableDataAttributes addNameItem(String nameItem) {
    if (this.name == null) {
      this.name = new ArrayList<>();
    }
    this.name.add(nameItem);
    return this;
  }

  /**
  * List of aggregated asset names
  * @return name
  **/
  @Schema(description = "List of aggregated asset names")
  public List<String> getName() {
    return name;
  }
  public void setName(List<String> name) {
    this.name = name;
  }
  public JsonApiModelScanTableDataAttributes type(List<String> type) {
    this.type = type;
    return this;
  }

  public JsonApiModelScanTableDataAttributes addTypeItem(String typeItem) {
    if (this.type == null) {
      this.type = new ArrayList<>();
    }
    this.type.add(typeItem);
    return this;
  }

  /**
  * List of aggregated asset types
  * @return type
  **/
  @Schema(description = "List of aggregated asset types")
  public List<String> getType() {
    return type;
  }
  public void setType(List<String> type) {
    this.type = type;
  }
  public JsonApiModelScanTableDataAttributes user(List<String> user) {
    this.user = user;
    return this;
  }

  public JsonApiModelScanTableDataAttributes addUserItem(String userItem) {
    if (this.user == null) {
      this.user = new ArrayList<>();
    }
    this.user.add(userItem);
    return this;
  }

  /**
  * List of aggregated usernames
  * @return user
  **/
  @Schema(description = "List of aggregated usernames")
  public List<String> getUser() {
    return user;
  }
  public void setUser(List<String> user) {
    this.user = user;
  }
  public JsonApiModelScanTableDataAttributes resourceList(List<String> resourceList) {
    this.resourceList = resourceList;
    return this;
  }

  public JsonApiModelScanTableDataAttributes addResourceListItem(String resourceListItem) {
    if (this.resourceList == null) {
      this.resourceList = new ArrayList<>();
    }
    this.resourceList.add(resourceListItem);
    return this;
  }

  /**
  * List of aggregated resource lists
  * @return resourceList
  **/
  @Schema(description = "List of aggregated resource lists")
  public List<String> getResourceList() {
    return resourceList;
  }
  public void setResourceList(List<String> resourceList) {
    this.resourceList = resourceList;
  }
  public JsonApiModelScanTableDataAttributes tags(List<IacScanTag> tags) {
    this.tags = tags;
    return this;
  }

  public JsonApiModelScanTableDataAttributes addTagsItem(IacScanTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
  * List of aggregated tags
  * @return tags
  **/
  @Schema(description = "List of aggregated tags")
  public List<IacScanTag> getTags() {
    return tags;
  }
  public void setTags(List<IacScanTag> tags) {
    this.tags = tags;
  }
  public JsonApiModelScanTableDataAttributes failureCriteria(String failureCriteria) {
    this.failureCriteria = failureCriteria;
    return this;
  }

  

  /**
  * Last failure criteria expression in the aggregated scan result
  * @return failureCriteria
  **/
  @Schema(description = "Last failure criteria expression in the aggregated scan result")
  public String getFailureCriteria() {
    return failureCriteria;
  }
  public void setFailureCriteria(String failureCriteria) {
    this.failureCriteria = failureCriteria;
  }
  public JsonApiModelScanTableDataAttributes status(JsonApiModelScanStatus status) {
    this.status = status;
    return this;
  }

  

  /**
  * Get status
  * @return status
  **/
  @Schema(description = "")
  public JsonApiModelScanStatus getStatus() {
    return status;
  }
  public void setStatus(JsonApiModelScanStatus status) {
    this.status = status;
  }
  public JsonApiModelScanTableDataAttributes merged(Boolean merged) {
    this.merged = merged;
    return this;
  }

  

  /**
  * If or not the last scan is merged in the aggregated result
  * @return merged
  **/
  @Schema(description = "If or not the last scan is merged in the aggregated result")
  public Boolean isMerged() {
    return merged;
  }
  public void setMerged(Boolean merged) {
    this.merged = merged;
  }
  public JsonApiModelScanTableDataAttributes deployed(Boolean deployed) {
    this.deployed = deployed;
    return this;
  }

  

  /**
  * If or not the last scan is deployed in the aggregated result
  * @return deployed
  **/
  @Schema(description = "If or not the last scan is deployed in the aggregated result")
  public Boolean isDeployed() {
    return deployed;
  }
  public void setDeployed(Boolean deployed) {
    this.deployed = deployed;
  }
  public JsonApiModelScanTableDataAttributes fail(Long fail) {
    this.fail = fail;
    return this;
  }

  

  /**
  * Number of failed scans in the aggregated result
  * @return fail
  **/
  @Schema(description = "Number of failed scans in the aggregated result")
  public Long getFail() {
    return fail;
  }
  public void setFail(Long fail) {
    this.fail = fail;
  }
  public JsonApiModelScanTableDataAttributes pass(Long pass) {
    this.pass = pass;
    return this;
  }

  

  /**
  * Number of passed scans in the aggregated result
  * @return pass
  **/
  @Schema(description = "Number of passed scans in the aggregated result")
  public Long getPass() {
    return pass;
  }
  public void setPass(Long pass) {
    this.pass = pass;
  }
  public JsonApiModelScanTableDataAttributes matchedPoliciesSummary(IacMatchedPoliciesSummary matchedPoliciesSummary) {
    this.matchedPoliciesSummary = matchedPoliciesSummary;
    return this;
  }

  

  /**
  * Get matchedPoliciesSummary
  * @return matchedPoliciesSummary
  **/
  @Schema(description = "")
  public IacMatchedPoliciesSummary getMatchedPoliciesSummary() {
    return matchedPoliciesSummary;
  }
  public void setMatchedPoliciesSummary(IacMatchedPoliciesSummary matchedPoliciesSummary) {
    this.matchedPoliciesSummary = matchedPoliciesSummary;
  }
  public JsonApiModelScanTableDataAttributes scanAttributes(JsonApiModelScanAttributes scanAttributes) {
    this.scanAttributes = scanAttributes;
    return this;
  }

  

  /**
  * Get scanAttributes
  * @return scanAttributes
  **/
  @Schema(description = "")
  public JsonApiModelScanAttributes getScanAttributes() {
    return scanAttributes;
  }
  public void setScanAttributes(JsonApiModelScanAttributes scanAttributes) {
    this.scanAttributes = scanAttributes;
  }
  public JsonApiModelScanTableDataAttributes scanTime(OffsetDateTime scanTime) {
    this.scanTime = scanTime;
    return this;
  }

  

  /**
  * Latest scan time in the aggregated result
  * @return scanTime
  **/
  @Schema(description = "Latest scan time in the aggregated result")
  public OffsetDateTime getScanTime() {
    return scanTime;
  }
  public void setScanTime(OffsetDateTime scanTime) {
    this.scanTime = scanTime;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelScanTableDataAttributes jsonApiModelScanTableDataAttributes = (JsonApiModelScanTableDataAttributes) o;
    return Objects.equals(this.name, jsonApiModelScanTableDataAttributes.name) &&
        Objects.equals(this.type, jsonApiModelScanTableDataAttributes.type) &&
        Objects.equals(this.user, jsonApiModelScanTableDataAttributes.user) &&
        Objects.equals(this.resourceList, jsonApiModelScanTableDataAttributes.resourceList) &&
        Objects.equals(this.tags, jsonApiModelScanTableDataAttributes.tags) &&
        Objects.equals(this.failureCriteria, jsonApiModelScanTableDataAttributes.failureCriteria) &&
        Objects.equals(this.status, jsonApiModelScanTableDataAttributes.status) &&
        Objects.equals(this.merged, jsonApiModelScanTableDataAttributes.merged) &&
        Objects.equals(this.deployed, jsonApiModelScanTableDataAttributes.deployed) &&
        Objects.equals(this.fail, jsonApiModelScanTableDataAttributes.fail) &&
        Objects.equals(this.pass, jsonApiModelScanTableDataAttributes.pass) &&
        Objects.equals(this.matchedPoliciesSummary, jsonApiModelScanTableDataAttributes.matchedPoliciesSummary) &&
        Objects.equals(this.scanAttributes, jsonApiModelScanTableDataAttributes.scanAttributes) &&
        Objects.equals(this.scanTime, jsonApiModelScanTableDataAttributes.scanTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, user, resourceList, tags, failureCriteria, status, merged, deployed, fail, pass, matchedPoliciesSummary, scanAttributes, scanTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScanTableDataAttributes {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    resourceList: ").append(toIndentedString(resourceList)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    failureCriteria: ").append(toIndentedString(failureCriteria)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    merged: ").append(toIndentedString(merged)).append("\n");
    sb.append("    deployed: ").append(toIndentedString(deployed)).append("\n");
    sb.append("    fail: ").append(toIndentedString(fail)).append("\n");
    sb.append("    pass: ").append(toIndentedString(pass)).append("\n");
    sb.append("    matchedPoliciesSummary: ").append(toIndentedString(matchedPoliciesSummary)).append("\n");
    sb.append("    scanAttributes: ").append(toIndentedString(scanAttributes)).append("\n");
    sb.append("    scanTime: ").append(toIndentedString(scanTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
