/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * JsonApiModelAsyncScanRequestDataAttributes
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelAsyncScanRequestDataAttributes {

  @JsonProperty("assetName")

  private String assetName = null;

  @JsonProperty("assetType")

  private String assetType = null;

  @JsonProperty("tags")

  private Map<String, String> tags = null;

  @JsonProperty("scanAttributes")

  private JsonApiModelScanAttributes scanAttributes = null;

  @JsonProperty("failureCriteria")

  private JsonApiModelFailureCriteria failureCriteria = null;
  public JsonApiModelAsyncScanRequestDataAttributes assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

  

  /**
  * Registered asset name (255 character limit) that will appear as the resource name in the Prisma Cloud Devops Inventory
  * @return assetName
  **/
  @Schema(example = "my-asset", required = true, description = "Registered asset name (255 character limit) that will appear as the resource name in the Prisma Cloud Devops Inventory")
  public String getAssetName() {
    return assetName;
  }
  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }
  public JsonApiModelAsyncScanRequestDataAttributes assetType(String assetType) {
    this.assetType = assetType;
    return this;
  }

  

  /**
  * Supported asset types: * AzureDevOps: Azure DevOps Services * AWSCodePipeline: AWS CodePipeline * BitbucketServer: Bitbucket server * BitbucketCloud: Bitbucket Cloud * CircleCI: CircleCI project * GitHub: GitHub repo * GitLab-CICD: GitLab CI/CD Pipeline * GitLab-SCM: GitLab SCM Webhook * IaC-API: direct IAC API attachment * IntelliJ: IntelliJ IDE plugin managed files * Jenkins: Jenkins build server * VSCode: VSCode plugin managed files * twistcli: Twistlock CLI attachment 
  * @return assetType
  **/
  @Schema(example = "AzureDevOps", required = true, description = "Supported asset types: * AzureDevOps: Azure DevOps Services * AWSCodePipeline: AWS CodePipeline * BitbucketServer: Bitbucket server * BitbucketCloud: Bitbucket Cloud * CircleCI: CircleCI project * GitHub: GitHub repo * GitLab-CICD: GitLab CI/CD Pipeline * GitLab-SCM: GitLab SCM Webhook * IaC-API: direct IAC API attachment * IntelliJ: IntelliJ IDE plugin managed files * Jenkins: Jenkins build server * VSCode: VSCode plugin managed files * twistcli: Twistlock CLI attachment ")
  public String getAssetType() {
    return assetType;
  }
  public void setAssetType(String assetType) {
    this.assetType = assetType;
  }
  public JsonApiModelAsyncScanRequestDataAttributes tags(Map<String, String> tags) {
    this.tags = tags;
    return this;
  }

  
  public JsonApiModelAsyncScanRequestDataAttributes putTagsItem(String key, String tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }
  /**
  * Tags assigned to the asset or the scan job. Both tag key and value have 255 character limit.
  * @return tags
  **/
  @Schema(example = "{\"env\":\"dev\",\"region\":\"us-west-1\"}", description = "Tags assigned to the asset or the scan job. Both tag key and value have 255 character limit.")
  public Map<String, String> getTags() {
    return tags;
  }
  public void setTags(Map<String, String> tags) {
    this.tags = tags;
  }
  public JsonApiModelAsyncScanRequestDataAttributes scanAttributes(JsonApiModelScanAttributes scanAttributes) {
    this.scanAttributes = scanAttributes;
    return this;
  }

  

  /**
  * Get scanAttributes
  * @return scanAttributes
  **/
  @Schema(description = "")
  public JsonApiModelScanAttributes getScanAttributes() {
    return scanAttributes;
  }
  public void setScanAttributes(JsonApiModelScanAttributes scanAttributes) {
    this.scanAttributes = scanAttributes;
  }
  public JsonApiModelAsyncScanRequestDataAttributes failureCriteria(JsonApiModelFailureCriteria failureCriteria) {
    this.failureCriteria = failureCriteria;
    return this;
  }

  

  /**
  * Get failureCriteria
  * @return failureCriteria
  **/
  @Schema(description = "")
  public JsonApiModelFailureCriteria getFailureCriteria() {
    return failureCriteria;
  }
  public void setFailureCriteria(JsonApiModelFailureCriteria failureCriteria) {
    this.failureCriteria = failureCriteria;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelAsyncScanRequestDataAttributes jsonApiModelAsyncScanRequestDataAttributes = (JsonApiModelAsyncScanRequestDataAttributes) o;
    return Objects.equals(this.assetName, jsonApiModelAsyncScanRequestDataAttributes.assetName) &&
        Objects.equals(this.assetType, jsonApiModelAsyncScanRequestDataAttributes.assetType) &&
        Objects.equals(this.tags, jsonApiModelAsyncScanRequestDataAttributes.tags) &&
        Objects.equals(this.scanAttributes, jsonApiModelAsyncScanRequestDataAttributes.scanAttributes) &&
        Objects.equals(this.failureCriteria, jsonApiModelAsyncScanRequestDataAttributes.failureCriteria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetName, assetType, tags, scanAttributes, failureCriteria);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelAsyncScanRequestDataAttributes {\n");
    
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    scanAttributes: ").append(toIndentedString(scanAttributes)).append("\n");
    sb.append("    failureCriteria: ").append(toIndentedString(failureCriteria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
