/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.HashMap;
import java.util.Objects;

/**
 * Additonal attributes associated with the IaC scan job. The keys below should be used for better display: * buildNumber: For CI/CD, the build number associated with the IaC scan * projectName: For CI/CD, the repo or project name associated with the IaC scan * prName: For CI/CD, the pull/merge request name associated with the IaC scan * pipelineName: For CD pipeline, the pipeline name associated with the IaC scan * pipelineLambda: For CD pipeline, the lambda name associated with the IaC scan * pipelineJobId: For CD pipeline, the job ID associated with the IaC scan * pipelineStageName: For CD pipeline, the stage name associated with the IaC scan * pipelineActionName: For CD pipeline, the action name associated with the IaC scan 
 */
@Schema(description = "Additonal attributes associated with the IaC scan job. The keys below should be used for better display: * buildNumber: For CI/CD, the build number associated with the IaC scan * projectName: For CI/CD, the repo or project name associated with the IaC scan * prName: For CI/CD, the pull/merge request name associated with the IaC scan * pipelineName: For CD pipeline, the pipeline name associated with the IaC scan * pipelineLambda: For CD pipeline, the lambda name associated with the IaC scan * pipelineJobId: For CD pipeline, the job ID associated with the IaC scan * pipelineStageName: For CD pipeline, the stage name associated with the IaC scan * pipelineActionName: For CD pipeline, the action name associated with the IaC scan ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScanAttributes extends HashMap<String, String> {
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScanAttributes {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
