/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Relationships to the scan result
 */
@Schema(description = "Relationships to the scan result")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScanTableDataRelationships {

  @JsonProperty("scanResult")

  private JsonApiModelScanTableDataRelationshipsScanResult scanResult = null;
  public JsonApiModelScanTableDataRelationships scanResult(JsonApiModelScanTableDataRelationshipsScanResult scanResult) {
    this.scanResult = scanResult;
    return this;
  }

  

  /**
  * Get scanResult
  * @return scanResult
  **/
  @Schema(description = "")
  public JsonApiModelScanTableDataRelationshipsScanResult getScanResult() {
    return scanResult;
  }
  public void setScanResult(JsonApiModelScanTableDataRelationshipsScanResult scanResult) {
    this.scanResult = scanResult;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelScanTableDataRelationships jsonApiModelScanTableDataRelationships = (JsonApiModelScanTableDataRelationships) o;
    return Objects.equals(this.scanResult, jsonApiModelScanTableDataRelationships.scanResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scanResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScanTableDataRelationships {\n");
    
    sb.append("    scanResult: ").append(toIndentedString(scanResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
