/*
 * IaC Scan API Version 2
 * The IaC scan-service receives and assesses customer IaC resources
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.prismacloud.iac.commons.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Scan result object related to the scan
 */
@Schema(description = "Scan result object related to the scan")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T11:29:52.304914+05:30[Asia/Kolkata]")public class JsonApiModelScanTableDataRelationshipsScanResult {

  @JsonProperty("links")

  private JsonApiModelScanTableDataRelationshipsScanResultLinks links = null;
  public JsonApiModelScanTableDataRelationshipsScanResult links(JsonApiModelScanTableDataRelationshipsScanResultLinks links) {
    this.links = links;
    return this;
  }

  

  /**
  * Get links
  * @return links
  **/
  @Schema(description = "")
  public JsonApiModelScanTableDataRelationshipsScanResultLinks getLinks() {
    return links;
  }
  public void setLinks(JsonApiModelScanTableDataRelationshipsScanResultLinks links) {
    this.links = links;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonApiModelScanTableDataRelationshipsScanResult jsonApiModelScanTableDataRelationshipsScanResult = (JsonApiModelScanTableDataRelationshipsScanResult) o;
    return Objects.equals(this.links, jsonApiModelScanTableDataRelationshipsScanResult.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonApiModelScanTableDataRelationshipsScanResult {\n");
    
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
